apiVersion: v1
kind: Secret
metadata:
  name: meetx-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.secrets.pgadminPassword | quote }}
  JWT_KEY: {{ .Values.secrets.jwtKey | quote }}
  REFRESH_JWT_KEY: {{ .Values.secrets.refreshJwtKey | quote }}
  LINKEDIN_CLIENT_SECRET: {{ .Values.secrets.linkedinClientSecret | quote }}
  MAIL_PASSWORD: {{ .Values.secrets.mailPassword | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
