apiVersion: v2
name: portainer
description: A wrapper Helm chart for the official Portainer dashboard
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: portainer
    version: "2.33.6"
    repository: "https://portainer.github.io/k8s/"
# Command captured from previous version:
# helm upgrade --install --create-namespace -n portainer portainer portainer/portainer \
#     --set service.type=ClusterIP \
#     --set image.tag=lts \
#     --set ingress.enabled=true \
#     --set ingress.annotations."nginx\.ingress\.kubernetes\.io/backend-protocol"=HTTP \
#     --set ingress.hosts[0].host=portainer.meetx.local \
#     --set ingress.hosts[0].paths[0].path="/"
