apiVersion: v2
name: portainer
description: A wrapper Helm chart for the official Portainer dashboard
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: portainer
    version: "2.33.6"
    repository: "https://portainer.github.io/k8s/"
