portainer:
  service:
    type: ClusterIP
  
  image:
    tag: lts
  
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: portainer.meetx.local
        paths:
          - path: "/"
