apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meetx-ingress
  namespace: meetx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: meetx.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: meetx
            port:
              number: 80
  - host: auth.meetx.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server-auth
            port:
              number: 3001
  - host: api.meetx.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server-dotnet
            port:
              number: 8080
  - host: pgadmin.meetx.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin
            port:
              number: 8888
