apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetx
  namespace: meetx
spec:
  selector:
    matchLabels:
      app: meetx
  template:
    metadata:
      labels:
        app: meetx
    spec:
      containers:
      - name: meetx
        image: meetx-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: meetx
  namespace: meetx
spec:
  type: ClusterIP
  selector:
    app: meetx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80