apiVersion: v1
kind: Secret
metadata:
  name: meetx-secrets
  namespace: meetx
type: Opaque
stringData:
  POSTGRES_PASSWORD: "meetx"
  PGADMIN_DEFAULT_PASSWORD: "admin"
  JWT_KEY: "SecretKey00000000000000000000000"
  REFRESH_JWT_KEY: "SecretKey19897340935095882903589"
  LINKEDIN_CLIENT_SECRET: "WPL_AP0.UZCau3vqoHJiFhCe.MjI2Mzg3MTQ5Mw=="
  MAIL_PASSWORD: "d1d27bd6b46e56"
  ADMIN_PASSWORD: "admin123"
