apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-auth
  namespace: meetx
spec:
  selector:
    matchLabels:
      app: server-auth
  template:
    metadata:
      labels:
        app: server-auth
    spec:
      containers:
      - name: server-auth
        image: meetx-server-auth:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: meetx-secrets
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://meetx:$(POSTGRES_PASSWORD)@meetx-db:5432/meetx"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: meetx-secrets
              key: JWT_KEY
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: meetx-secrets
              key: REFRESH_JWT_KEY
        - name: JWT_ACCESS_EXPIRATION
          value: "15m"
        - name: JWT_REFRESH_EXPIRATION
          value: "7d"
        - name: CORS_ORIGIN
          value: "http://localhost:3001,http://localhost:8080,http://localhost:80,http://localhost,http://meetx,http://server-dotnet"
        - name: ADMIN_EMAIL
          value: "admin@meetx.com"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: meetx-secrets
              key: ADMIN_PASSWORD
        - name: DB_PATH
          value: "/app/data/users.json"
        - name: AUTH_URL
          value: "http://auth.meetx.local"
        - name: FRONTEND_URL
          value: "http://meetx.local"
        - name: BACKEND_URL
          value: "http://api.meetx.local"
        - name: MAIL_HOST
          value: "sandbox.smtp.mailtrap.io"
        - name: MAIL_PORT
          value: "2525"
        - name: MAIL_USER
          value: "63cfb840afb0b1"
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: meetx-secrets
              key: MAIL_PASSWORD
        - name: MAIL_FROM
          value: "team@meetx.com"
---
apiVersion: v1
kind: Service
metadata:
  name: server-auth
  namespace: meetx
spec:
  type: ClusterIP
  selector:
    app: server-auth
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
