apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetx
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: meetx
  template:
    metadata:
      labels:
        app: meetx
    spec:
      containers:
      - name: meetx
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: meetx
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: meetx
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: 80
