apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetx
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: meetx
  template:
    metadata:
      labels:
        app: meetx
    spec:
      containers:
      - name: meetx
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 80
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:1.1.0
        imagePullPolicy: IfNotPresent
        args:
          - -nginx.scrape-uri=http://127.0.0.1:80/stub_status
        ports:
        - containerPort: 9113
          name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: meetx
  namespace: {{ .Release.Namespace }}
  labels:
    app: meetx
spec:
  type: ClusterIP
  selector:
    app: meetx
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: 80
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: 9113
