apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-claim
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetx-db
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: meetx-db
  template:
    metadata:
      labels:
        app: meetx-db
    spec:
      containers:
      - name: meetx-db
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        imagePullPolicy: {{ .Values.db.image.pullPolicy }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: {{ .Values.db.env.postgresUser | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.db.env.postgresDb | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: meetx-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: meetx-db
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: meetx-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
